### ISSUE TITLE
Node.js packages are outdated

### ISSUE THREAD

**Issue by lingxiaoyang** [savoirfairelinux/sous-chef#627] opened 2017-01-18 20:50 UTC
### Expected Behaviour

We use `gulp` to generate static assets (images, CS, JS, etc.), and we should make sure that the Node.js dependencies are up-to-date. This is not directly related to the functionality or security of sous-chef, but fixing it would eliminate potential maintenance problems in the future.

### Actual Behaviour

Using `docker-compose`, sous-chef is automatically built with outdated Node.js, npm, and even a deprecated package. It caused a deployment error recently due to a malfunction of an old npm version. (The error is related to gifsicle ENOENT, but for this moment we have a temporary solution for it.)

1. Outdated Node.js and npm
    On Ubuntu, `apt-get install nodejs` is not getting the newest version of nodejs and npm:
````
root@525e47d51809:/code# nodejs --version                                                                                                  
v4.7.2
root@525e47d51809:/code# npm --version
2.15.11
````
(The latest versions are node.js==6.9.4LTS and npm==4.1.1)

*Note: to install the newest nodejs and npm see [here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions). To install only the newest npm, it's also possible:*
````
root@525e47d51809:/code# npm --version
2.15.11
root@525e47d51809:/code# npm -g install npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
npm@4.1.1 /usr/lib/node_modules/npm
root@525e47d51809:/code# npm --version
4.1.1
````

2. Deprecated package:
````
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN optional dep failed, continuing fsevents@1.0.17
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing fsevents@1.0.17
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
````
    `gulp-minify-css` has been deprecated and replaced. It introduces a few deprecated packages also.

3. Outdated packages:
    Tested with `npm -g install npm-check-updates`:
````
root@525e47d51809:/code/tools/gulp# npm-check-updates 
[INFO]: You can also use ncu as an alias
Using /code/tools/gulp/package.json
[..................] - :
 es6-promise      ^3.0.2  →  ^4.0.5 
 gulp-debug       ^2.1.2  →  ^3.0.0 
 gulp-imagemin    ^2.4.0  →  ^3.1.1 
 gulp-jsvalidate  ^2.1.0  →  ^3.0.0 
 gulp-sass        ^2.1.0  →  ^3.1.0 
 gulp-uglify      ^1.4.2  →  ^2.0.0 
````

### Steps to reproduce

N/A

**Comment by ventilooo** [comment] 2017-01-19 16:33
Long term solution :

* [bithound](https://github.com/integrations/bithound)
* [versioneye](https://github.com/integrations/versioneye)

**Comment by lingxiaoyang** [comment] 2017-01-19 23:28
@ventilooo Thank you, these are very cool!

JS:
![image](https://cloud.githubusercontent.com/assets/8630726/22129596/f91fcaae-de74-11e6-8b42-51f6ad07ac46.png)

Python:
![image](https://cloud.githubusercontent.com/assets/8630726/22129623/1fbaecf2-de75-11e6-99c9-a0d473670c1d.png)

**Comment by peakwinter** [comment] 2017-03-17 18:49
Along the same lines, would it be worth it to remove the hardcoded files in `src/frontend/{js,scss}/vendor` and instead install them from NPM + pack them in with Gulp? I see at least one file that has local modifications from its source version, but in that case we could use NPM to install from a forked Github repo. That way we could still periodically merge in upstream improvements.

**Comment by erozqba** [comment] 2017-03-20 22:55
@peakwinter :+1:  could you submit a PR?

**Comment by peakwinter** [comment] 2017-03-21 14:59
@erozqba Will do!

@lingxiaoyang After looking into it, the deprecation notices appear to be caused by Gulp and shouldn't effect us very much. They should be fixed when Gulp hits 4.x.

**Comment by lingxiaoyang** [comment] 2017-03-21 15:12
@peakwinter  On versioneye I muted the JS packages. You can re-enable them if you feel necessary.

**Closed** 2017-03-21 19:28 UTC
Labels: beginner, deployment, not urgent
